services:
  nginx:
    build:
      context: portfolio
      target: ngi
    image: nginx:latest
    volumes:
      - ./portfolio/dist/portfolio:/usr/share/nginx/html
      - ./portfolio/default.conf:/etc/nginx/conf.d/default.conf
      #- type: bind
      #  source: ./portfolio/nginx.conf
      #  target: /etc/nginx/nginx.conf
    ports:
      - 80:80

  #web:
  #  build:
  #    context: portfolio
  #    target: builder
  #  ports:
  #    - 8080:8080
  #  volumes:
  #    - ./portfolio:/project
  #    - /project/node_modules
