services:
  web:
    build:
      context: portfolio
      target: dev-envs
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portfolio:/project
      - /project/node_modules
